//! The command-running check kinds: `tests_pass`, `coverage_min`,
//! `lint_clean`, `complexity_clean`, `--partial`, `--no-run`, and the
//! `degraded` flag.
//!
//! Every fake command is `exit 0` or `exit 1`, which both `cmd.exe /C` and
//! `/bin/sh -c` accept, so no fixture needs a script file or a shebang. Every
//! coverage artifact is written from Rust rather than generated by a command.

mod common;

use assert_cmd::Command;
use common::Project;
use devforgeai::config::{Config, Stack};

fn cli(p: &Project) -> Command {
    let mut c = Command::cargo_bin("devforgeai").expect("the binary builds");
    c.arg("--project").arg(p.root());
    c.current_dir(p.root());
    c
}

fn gate(p: &Project, args: &[&str]) -> (i32, String, String) {
    let out = cli(p)
        .args(["gate", "check", "--phase", "build", "--id", "STORY-014"])
        .args(args)
        .output()
        .expect("run");
    (
        out.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&out.stdout).to_string(),
        String::from_utf8_lossy(&out.stderr).to_string(),
    )
}

fn gate_json(p: &Project, args: &[&str]) -> serde_json::Value {
    let out = cli(p)
        .args([
            "--json",
            "gate",
            "check",
            "--phase",
            "build",
            "--id",
            "STORY-014",
        ])
        .args(args)
        .output()
        .expect("run");
    let text = String::from_utf8_lossy(&out.stdout).to_string();
    serde_json::from_str(text.trim()).unwrap_or_else(|e| panic!("{e} in {text}"))
}

/// The build gate, with the three required kinds plus whatever `extra` adds.
fn gates(extra: &str) -> String {
    format!(
        r#"schema = "devforgeai/gates/1"
cli_min_version = "1.0.0"

[[gate]]
phase = "build"
requires = ""
on_fail = "fail"

  [[gate.check]]
  kind = "doc_valid"
  id = "build-docs"
  docs = ["stories/STORY-014.md"]

  [[gate.check]]
  kind = "tests_pass"
  id = "build-tests"

  [[gate.check]]
  kind = "coverage_min"
  id = "build-coverage"
  source = "read"

{extra}"#
    )
}

/// A `[[stack]]` whose four commands are the fakes the test wants.
fn stack(test: &str, coverage: &str, lint: &str, complexity: &str) -> Stack {
    Stack {
        id: "rust".into(),
        markers: vec!["Cargo.toml".into()],
        package_manager: "cargo".into(),
        source_roots: vec!["src".into()],
        test_command: test.into(),
        coverage_command: coverage.into(),
        lint_command: lint.into(),
        complexity_command: complexity.into(),
        coverage_format: "lcov".into(),
        coverage_paths: vec!["cov/lcov.info".into()],
        timeout_secs: 60,
        ..Default::default()
    }
}

/// An lcov artifact: one domain file and one interface file.
const LCOV: &str = "TN:\nSF:src/domain/order.rs\nDA:1,1\nDA:2,1\nDA:3,1\nDA:4,1\nDA:5,1\nDA:6,1\nDA:7,1\nDA:8,1\nDA:9,1\nDA:10,1\nend_of_record\nSF:src/api/http.rs\nDA:1,1\nDA:2,1\nDA:3,1\nDA:4,1\nDA:5,1\nDA:6,1\nDA:7,1\nDA:8,0\nDA:9,0\nDA:10,0\nend_of_record\n";

fn seeded(s: Stack, extra: &str) -> Project {
    let p = Project::new();
    p.write(
        ".devforgeai/stories/STORY-014.md",
        &common::story("STORY-014", "building", &[], "# Order checkout\n"),
    );
    p.write(".devforgeai/gates.toml", &gates(extra));
    p.write("cov/lcov.info", LCOV);
    let degraded = s.id.is_empty();
    p.write_config(&Config {
        degraded,
        stack: if degraded { vec![] } else { vec![s] },
        generated_at: "2026-09-10T14:02:11Z".into(),
        ..Default::default()
    });
    p.set_phase("build", "STORY-014");
    p
}

fn status_of(v: &serde_json::Value, id: &str) -> String {
    v["data"]["checks"]
        .as_array()
        .expect("checks")
        .iter()
        .find(|c| c["id"] == id)
        .unwrap_or_else(|| panic!("check {id} in {v}"))["status"]
        .as_str()
        .unwrap_or("")
        .to_string()
}

fn reason_of(v: &serde_json::Value, id: &str) -> String {
    v["data"]["checks"]
        .as_array()
        .expect("checks")
        .iter()
        .find(|c| c["id"] == id)
        .unwrap_or_else(|| panic!("check {id} in {v}"))["reason"]
        .as_str()
        .unwrap_or("")
        .to_string()
}

// ------------------------------------------------------------- tests_pass

#[test]
fn a_test_command_that_exits_zero_passes() {
    let p = seeded(stack("exit 0", "exit 0", "", ""), "");
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-tests"), "pass", "{v}");
}

#[test]
fn a_test_command_that_exits_one_fails_with_e311() {
    let p = seeded(stack("exit 1", "exit 0", "", ""), "");
    let (code, _, _) = gate(&p, &[]);
    assert_eq!(code, 1);
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-tests"), "fail");
    assert!(reason_of(&v, "build-tests").contains("DFA-E311"), "{v}");
}

#[test]
fn an_empty_test_command_fails_with_e310_when_the_stack_is_detected() {
    let p = seeded(stack("", "exit 0", "", ""), "");
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-tests"), "fail");
    assert!(reason_of(&v, "build-tests").contains("DFA-E310"), "{v}");
}

#[test]
fn allow_empty_lets_an_empty_test_command_pass() {
    let p = seeded(
        stack("", "exit 0", "", ""),
        "  [[gate.check]]\n  kind = \"tests_pass\"\n  id = \"build-tests-2\"\n  allow_empty = true\n",
    );
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-tests-2"), "pass", "{v}");
}

#[test]
fn the_evidence_carries_the_command_the_code_and_the_counts() {
    let p = seeded(stack("exit 0", "exit 0", "", ""), "");
    let v = gate_json(&p, &[]);
    let e = &v["data"]["checks"]
        .as_array()
        .expect("checks")
        .iter()
        .find(|c| c["id"] == "build-tests")
        .expect("the check")["evidence"];
    assert_eq!(e["command"], "exit 0");
    assert_eq!(e["exit_code"], 0);
    assert!(e["duration_ms"].is_number(), "{e}");
    assert!(e["output_tail"].is_string(), "{e}");
    assert!(
        e["passed"].is_null(),
        "an unmatched pattern leaves the count null, not zero: {e}"
    );
}

#[test]
fn the_stacks_key_narrows_the_run() {
    let p = seeded(
        stack("exit 1", "exit 0", "", ""),
        "  [[gate.check]]\n  kind = \"tests_pass\"\n  id = \"build-tests-node\"\n  stacks = [\"node\"]\n",
    );
    let v = gate_json(&p, &[]);
    // A check that names a stack the project does not hold has nothing to run
    // and therefore nothing to prove. Passing it is the free pass: the gate
    // would report a green `tests_pass` for a test suite that never ran.
    assert_eq!(
        status_of(&v, "build-tests-node"),
        "fail",
        "a check whose named stack is absent fails rather than passing: {v}"
    );
    let reason = reason_of(&v, "build-tests-node");
    assert!(reason.contains("DFA-E310"), "{reason}");
    assert!(
        reason.contains("node"),
        "the absent stack is named: {reason}"
    );
}

// ------------------------------------------------------------- lint_clean

#[test]
fn a_lint_command_that_exits_one_fails_with_e315() {
    let p = seeded(
        stack("exit 0", "exit 0", "exit 1", ""),
        "  [[gate.check]]\n  kind = \"lint_clean\"\n  id = \"build-lint\"\n",
    );
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-lint"), "fail");
    assert!(reason_of(&v, "build-lint").contains("DFA-E315"), "{v}");
}

#[test]
fn an_empty_lint_command_is_a_skip_naming_its_reason() {
    let p = seeded(
        stack("exit 0", "exit 0", "", ""),
        "  [[gate.check]]\n  kind = \"lint_clean\"\n  id = \"build-lint\"\n",
    );
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-lint"), "skip");
    assert_eq!(reason_of(&v, "build-lint"), "no_lint_command");
    assert_eq!(v["exit"], 0, "a skip counts as passing");
}

// ------------------------------------------------------- complexity_clean

#[test]
fn an_empty_complexity_command_is_a_skip_naming_its_reason() {
    let p = seeded(
        stack("exit 0", "exit 0", "", ""),
        "  [[gate.check]]\n  kind = \"complexity_clean\"\n  id = \"build-complexity\"\n",
    );
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-complexity"), "skip");
    assert_eq!(reason_of(&v, "build-complexity"), "no_complexity_command");
}

#[test]
fn a_complexity_command_that_exits_one_fails() {
    let p = seeded(
        stack("exit 0", "exit 0", "", "exit 1"),
        "  [[gate.check]]\n  kind = \"complexity_clean\"\n  id = \"build-complexity\"\n",
    );
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-complexity"), "fail");
    assert!(
        reason_of(&v, "build-complexity").contains("complexity command"),
        "{v}"
    );
}

// ------------------------------------------------------------ coverage_min

#[test]
fn coverage_min_reads_the_artifact_and_fills_the_report_block() {
    let p = seeded(stack("exit 0", "exit 0", "", ""), "");
    let v = gate_json(&p, &[]);
    // domain 10/10 = 100.0, interface 7/10 = 70.0, overall 17/20 = 85.0.
    let c = &v["data"]["coverage"];
    assert_eq!(c["format"], "lcov");
    assert_eq!(c["source"], "cov/lcov.info");
    assert_eq!(c["overall"], 85.0, "{c}");
    let domain = c["layers"]
        .as_array()
        .expect("layers")
        .iter()
        .find(|l| l["name"] == "domain")
        .expect("domain");
    assert_eq!(domain["covered"], 10);
    assert_eq!(domain["total"], 10);
    assert_eq!(domain["percent"], 100.0);
    assert_eq!(domain["min"], 95.0);
    assert_eq!(domain["status"], "pass");

    let report = p.read(".devforgeai/reports/STORY-014-build.yaml");
    assert!(report.contains("coverage:"), "report was {report}");
    assert!(report.contains("overall: 85"), "report was {report}");
}

#[test]
fn a_layer_below_its_threshold_fails_with_e313() {
    let p = seeded(stack("exit 0", "exit 0", "", ""), "");
    // interface is 70.0 against the 70.0 default, so raise it.
    let mut cfg = devforgeai::config::load(p.root()).expect("config");
    for l in cfg.layer.iter_mut() {
        if l.name == "interface" {
            l.coverage_min = 90.0;
        }
    }
    p.write_config(&cfg);
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-coverage"), "fail");
    let reason = reason_of(&v, "build-coverage");
    assert!(reason.contains("DFA-E313"), "{reason}");
    assert!(reason.contains("interface"), "{reason}");
    assert!(reason.contains("70"), "{reason}");
}

#[test]
fn the_layers_key_narrows_the_check() {
    let p = seeded(
        stack("exit 0", "exit 0", "", ""),
        "  [[gate.check]]\n  kind = \"coverage_min\"\n  id = \"domain-only\"\n  source = \"read\"\n  layers = [\"domain\"]\n  overall = false\n",
    );
    let mut cfg = devforgeai::config::load(p.root()).expect("config");
    for l in cfg.layer.iter_mut() {
        if l.name == "interface" {
            l.coverage_min = 90.0;
        }
    }
    p.write_config(&cfg);
    let v = gate_json(&p, &[]);
    assert_eq!(
        status_of(&v, "domain-only"),
        "pass",
        "the interface shortfall is outside the named set: {v}"
    );
}

#[test]
fn the_overall_figure_is_checked_against_its_own_floor() {
    let p = seeded(stack("exit 0", "exit 0", "", ""), "");
    let mut cfg = devforgeai::config::load(p.root()).expect("config");
    cfg.coverage.overall_min = 90.0;
    p.write_config(&cfg);
    let v = gate_json(&p, &[]);
    let reason = reason_of(&v, "build-coverage");
    assert!(reason.contains("DFA-E313"), "{reason}");
    assert!(reason.contains("overall"), "{reason}");
}

#[test]
fn an_absent_artifact_is_e312() {
    let p = seeded(stack("exit 0", "exit 0", "", ""), "");
    std::fs::remove_file(p.root().join("cov").join("lcov.info")).expect("remove");
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-coverage"), "fail");
    assert!(reason_of(&v, "build-coverage").contains("DFA-E312"), "{v}");
}

#[test]
fn an_unparsable_artifact_is_e312() {
    let p = seeded(stack("exit 0", "exit 0", "", ""), "");
    p.write("cov/lcov.info", "not lcov at all\n");
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-coverage"), "fail");
    assert!(reason_of(&v, "build-coverage").contains("DFA-E312"), "{v}");
}

#[test]
fn every_format_parses_through_the_same_check() {
    for (format, path, body) in [
        (
            "cobertura",
            "cov/cobertura.xml",
            "<?xml version=\"1.0\"?><coverage><sources><source>.</source></sources><packages><package name=\"p\"><classes><class filename=\"src/domain/order.py\"><lines><line number=\"1\" hits=\"1\"/><line number=\"2\" hits=\"1\"/></lines></class></classes></package></packages></coverage>",
        ),
        (
            "jacoco",
            "cov/jacoco.xml",
            "<?xml version=\"1.0\"?><report name=\"r\"><package name=\"src/domain\"><sourcefile name=\"Order.java\"><counter type=\"LINE\" missed=\"0\" covered=\"10\"/></sourcefile></package></report>",
        ),
        (
            "go-cover",
            "cov/cover.out",
            "mode: set\nsrc/domain/order.go:3.20,5.2 4 1\n",
        ),
        (
            "devforgeai-json",
            "cov/coverage.json",
            "{ \"schema\": \"devforgeai/coverage/1\", \"files\": [ { \"path\": \"src/domain/order.rs\", \"covered\": 10, \"total\": 10 } ] }",
        ),
    ] {
        let mut s = stack("exit 0", "exit 0", "", "");
        s.coverage_format = format.to_string();
        s.coverage_paths = vec![path.to_string()];
        let p = seeded(s, "");
        std::fs::remove_file(p.root().join("cov").join("lcov.info")).expect("remove");
        p.write(path, body);

        let v = gate_json(&p, &[]);
        assert_eq!(status_of(&v, "build-coverage"), "pass", "{format}: {v}");
        assert_eq!(v["data"]["coverage"]["format"], format, "{format}");
        assert_eq!(
            v["data"]["coverage"]["overall"], 100.0,
            "{format}: {}",
            v["data"]["coverage"]
        );
    }
}

#[test]
fn source_read_runs_no_command() {
    // A coverage command that would fail is never reached under `source = "read"`.
    let p = seeded(stack("exit 0", "exit 1", "", ""), "");
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-coverage"), "pass", "{v}");
}

#[test]
fn an_unassigned_file_warns_under_the_report_policy() {
    let p = seeded(stack("exit 0", "exit 0", "", ""), "");
    p.write("cov/lcov.info", "SF:src/loose.rs\nDA:1,1\nend_of_record\n");
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-coverage"), "pass");
    assert!(reason_of(&v, "build-coverage").contains("DFA-W320"), "{v}");
    assert_eq!(v["data"]["coverage"]["unassigned"]["files"], 1);
}

#[test]
fn an_unassigned_file_fails_under_the_fail_policy() {
    let p = seeded(stack("exit 0", "exit 0", "", ""), "");
    p.write("cov/lcov.info", "SF:src/loose.rs\nDA:1,1\nend_of_record\n");
    let mut cfg = devforgeai::config::load(p.root()).expect("config");
    cfg.coverage.unassigned_policy = "fail".into();
    p.write_config(&cfg);
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-coverage"), "fail");
    assert!(reason_of(&v, "build-coverage").contains("DFA-E313"), "{v}");
}

#[test]
fn an_excluded_file_is_dropped_before_the_figures() {
    let p = seeded(stack("exit 0", "exit 0", "", ""), "");
    p.write(
        "cov/lcov.info",
        &format!("{LCOV}SF:src/tests/helper.rs\nDA:1,0\nDA:2,0\nend_of_record\n"),
    );
    let v = gate_json(&p, &[]);
    assert_eq!(
        v["data"]["coverage"]["overall"], 85.0,
        "the excluded file changed nothing: {}",
        v["data"]["coverage"]
    );
}

// ---------------------------------------------------------------- degraded

#[test]
fn a_degraded_project_skips_every_command_kind() {
    let mut s = stack("", "", "", "");
    s.id = String::new();
    let p = seeded(
        s,
        "  [[gate.check]]\n  kind = \"lint_clean\"\n  id = \"build-lint\"\n",
    );
    let v = gate_json(&p, &[]);
    assert_eq!(v["data"]["degraded"], true);
    for id in ["build-tests", "build-coverage", "build-lint"] {
        assert_eq!(status_of(&v, id), "skip", "{id}: {v}");
        assert_eq!(reason_of(&v, id), "degraded", "{id}");
    }
    assert_eq!(v["exit"], 0, "a skip counts as passing");

    // The degradation rule puts one line on stderr whenever the flag is set.
    let (_, _, err) = gate(&p, &[]);
    assert!(
        err.contains("Stack undetected; command checks skipped."),
        "stderr was {err}"
    );
}

#[test]
fn a_degraded_project_keeps_the_document_check() {
    let mut s = stack("", "", "", "");
    s.id = String::new();
    let p = seeded(s, "");
    let v = gate_json(&p, &[]);
    assert_eq!(status_of(&v, "build-docs"), "pass", "{v}");
}

// ----------------------------------------------------------------- --no-run

#[test]
fn no_run_skips_the_three_command_kinds_and_reads_coverage() {
    let p = seeded(
        stack("exit 1", "exit 1", "exit 1", "exit 1"),
        "  [[gate.check]]\n  kind = \"lint_clean\"\n  id = \"build-lint\"\n\n  [[gate.check]]\n  kind = \"complexity_clean\"\n  id = \"build-complexity\"\n",
    );
    let v = gate_json(&p, &["--no-run"]);
    for id in ["build-tests", "build-lint", "build-complexity"] {
        assert_eq!(status_of(&v, id), "skip", "{id}: {v}");
        assert_eq!(reason_of(&v, id), "no_run", "{id}");
    }
    assert_eq!(
        status_of(&v, "build-coverage"),
        "pass",
        "coverage still parses the file on disk: {v}"
    );
}

// ---------------------------------------------------------------- --partial

#[test]
fn partial_evaluates_only_the_four_command_kinds() {
    let p = seeded(
        stack("exit 0", "exit 0", "", ""),
        "  [[gate.check]]\n  kind = \"lint_clean\"\n  id = \"build-lint\"\n\n  [[gate.check]]\n  kind = \"complexity_clean\"\n  id = \"build-complexity\"\n",
    );
    let v = gate_json(&p, &["--partial"]);
    let ids: Vec<String> = v["data"]["checks"]
        .as_array()
        .expect("checks")
        .iter()
        .map(|c| c["id"].as_str().unwrap_or("").to_string())
        .collect();
    assert_eq!(
        ids,
        vec![
            "build-tests".to_string(),
            "build-coverage".to_string(),
            "build-lint".to_string(),
            "build-complexity".to_string()
        ],
        "the document check is not evaluated"
    );
    assert_eq!(v["data"]["partial"], true);
}

#[test]
fn partial_exits_zero_whatever_the_result_and_leaves_state_alone() {
    let p = seeded(stack("exit 1", "exit 0", "", ""), "");
    let before = p.state().last_gate.result.clone();
    let (code, _, _) = gate(&p, &["--partial"]);
    assert_eq!(code, 0, "--partial exits 0 whatever the result");
    let v = gate_json(&p, &["--partial"]);
    assert_eq!(status_of(&v, "build-tests"), "fail");
    assert_eq!(
        p.state().last_gate.result,
        before,
        "state.toml is untouched"
    );

    let report = p.read(".devforgeai/reports/STORY-014-build.yaml");
    assert!(report.contains("partial: true"), "report was {report}");
}
