apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "@@APP@@"
  labels:
    app: "@@APP@@"
spec:
  rules:
    - host: "@@APP@@.example.invalid"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "@@APP@@"
                port:
                  number: 80
