//! The `DFA-E<nnn>` / `DFA-W<nnn>` table, generated from the table in
//! `specs/01-cli.md` `## CLI calls` -> `Error and warning table`.
//!
//! This file is the single source of error identity for the binary. It is
//! regenerated from the spec and checked against it by
//! `tests/errors_table.rs::every_spec_code_appears_once`.

/// One row of the spec's error and warning table.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ErrorRow {
    /// The `DFA-E<nnn>` or `DFA-W<nnn>` identity.
    pub code: &'static str,
    /// The subcommand column, verbatim from the spec.
    pub subcommand: &'static str,
    /// The condition column, verbatim from the spec.
    pub condition: &'static str,
    /// The message column, with the surrounding backticks removed.
    pub message: &'static str,
    /// The process exit code this row maps to.
    pub exit: i32,
}

/// Every row of the spec table, in spec order. 149 entries.
pub const ERROR_TABLE: &[ErrorRow] = &[
    ErrorRow {
        code: "DFA-E010",
        subcommand: "any",
        condition: "unknown option or subcommand",
        message: "unknown option '<arg>'; run 'devforgeai --help'",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E011",
        subcommand: "any",
        condition: "required argument absent",
        message: "'<subcommand>' requires <arg>",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E012",
        subcommand: "any",
        condition: "value outside an enum",
        message: "'<value>' is not a <enum-name>; expected one of <a, b, c>",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E013",
        subcommand: "any",
        condition: "malformed ID",
        message: "'<value>' is not an ID; expected PREFIX-nnn with three digits, or it contradicts the id the document on disk carries",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E020",
        subcommand: "hook run",
        condition: "hook JSON lacks a key the event needs",
        message: "hook input has no key '<key>' for event <event>",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E021",
        subcommand: "hook run",
        condition: "stdin is not JSON",
        message: "stdin is not JSON: <parser message>",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E030",
        subcommand: "any",
        condition: "project root not found",
        message: "no .devforgeai/ directory in <cwd> or any ancestor; run 'devforgeai init'",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E031",
        subcommand: "any",
        condition: "`--project` path absent",
        message: "--project path '<path>' does not exist",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E101",
        subcommand: "any",
        condition: "`config.toml` absent",
        message: ".devforgeai/config.toml not found; run 'devforgeai stack detect'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E102",
        subcommand: "any",
        condition: "`gates.toml` absent",
        message: ".devforgeai/gates.toml not found; run 'devforgeai init'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E103",
        subcommand: "any",
        condition: "`state.toml` absent",
        message: ".devforgeai/state.toml not found; run 'devforgeai init'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E104",
        subcommand: "any",
        condition: "`config.toml` unparsable",
        message: "config.toml is not valid TOML: <parser message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E105",
        subcommand: "any",
        condition: "`gates.toml` unparsable",
        message: "gates.toml is not valid TOML: <parser message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E106",
        subcommand: "any",
        condition: "`state.toml` unparsable",
        message: "state.toml is not valid TOML: <parser message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E108",
        subcommand: "any",
        condition: "a key in a `state.toml` phase table is not in the schema",
        message: "state.toml [<phase>] has key '<key>', which the state schema does not define",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E107",
        subcommand: "any",
        condition: "`schema` key unknown",
        message: "<file>: schema '<value>' is unsupported; this binary reads <expected>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E110",
        subcommand: "init",
        condition: "`.devforgeai/config.toml` exists, no `--force`",
        message: "project is already initialised; pass --force to overwrite .devforgeai/",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E111",
        subcommand: "init",
        condition: "framework source not resolvable",
        message: "framework source not found; pass --from <path> to the DevForgeAI repo root",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E112",
        subcommand: "init",
        condition: "copy failed",
        message: "copying <src> to <dst> failed: <io message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E113",
        subcommand: "init --analyze",
        condition: "analysis time cap reached",
        message: "analysis stopped after 120s; <n> files unread",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-E120",
        subcommand: "design lint",
        condition: "`brand/tokens.json` absent",
        message: ".devforgeai/brand/tokens.json not found; the Design skill produces it",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E121",
        subcommand: "design lint",
        condition: "tokens JSON unparsable",
        message: "brand/tokens.json is not valid JSON: <parser message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E130",
        subcommand: "hook install",
        condition: "no `.git/` directory",
        message: "no .git directory; git hooks not installed",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-E131",
        subcommand: "hook install",
        condition: "`.claude/settings.json` unparsable",
        message: ".claude/settings.json is not valid JSON: <parser message>; nothing merged",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E132",
        subcommand: "hook install",
        condition: "a git hook exists that this binary did not write",
        message: "<hook> exists and is not a devforgeai hook; pass --force to replace it",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E200",
        subcommand: "doc validate, doc load",
        condition: "file absent",
        message: "<path> not found",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E201",
        subcommand: "doc validate",
        condition: "no frontmatter fence",
        message: "<path> has no frontmatter; line 1 opens with three dashes",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E202",
        subcommand: "doc validate",
        condition: "frontmatter is not a mapping",
        message: "<path> frontmatter is not a YAML mapping",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E203",
        subcommand: "doc validate",
        condition: "key absent",
        message: "<path> frontmatter has no key '<key>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E204",
        subcommand: "doc validate",
        condition: "extra top-level key",
        message: "<path> frontmatter has key '<key>', which conventions section 5 does not define",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E205",
        subcommand: "doc validate",
        condition: "keys out of order",
        message: "<path> frontmatter key '<key>' is at position <n>; conventions section 5 places it at <m>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E206",
        subcommand: "doc validate",
        condition: "wrong type",
        message: "<path> frontmatter key '<key>' is <actual>; expected <expected>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E207",
        subcommand: "doc validate",
        condition: "schema mismatch",
        message: "<path> schema is '<value>'; this document type is '<expected>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E208",
        subcommand: "doc validate",
        condition: "status outside the enum",
        message: "<path> status is '<value>'; <doc-type> allows <a, b, c>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E209",
        subcommand: "doc validate",
        condition: "ID malformed or duplicated",
        message: "<path> id '<value>' is malformed` / `<path> id '<value>' duplicates <other-path>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E210",
        subcommand: "doc validate",
        condition: "reference unresolved",
        message: "<path> references <ID>, which no document defines",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E211",
        subcommand: "doc validate",
        condition: "producer wrong for the doc type",
        message: "<path> produced_by is '<value>'; <doc-type> is produced by '<skill>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E212",
        subcommand: "doc validate --producer-check",
        condition: "current phase does not write this doc type",
        message: "phase '<current>' does not write <doc-type>; '<skill>' does",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E213",
        subcommand: "doc validate",
        condition: "heading absent or out of order",
        message: "<path> heading '<text>' is absent` / `<path> heading '<text>' is at position <n>, expected <m>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E214",
        subcommand: "doc validate --allocate",
        condition: "prefix outside §5",
        message: "'<prefix>' is not an ID prefix; conventions section 5 defines <list>",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E215",
        subcommand: "doc validate --allocate",
        condition: "prefix exhausted",
        message: "prefix <prefix> has no free ID below 999",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E216",
        subcommand: "doc validate",
        condition: "YAML document lacks a §5 top-level key",
        message: "<path> has no top-level key '<key>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E217",
        subcommand: "doc validate",
        condition: "a `release` document id is not a semver triple",
        message: "<path> id '<value>' is not vX.Y.Z",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E218",
        subcommand: "doc validate",
        condition: "a `release` version is not greater than the highest existing one",
        message: "<path> version <value> is not greater than <previous>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E220",
        subcommand: "context audit",
        condition: "context file absent",
        message: ".devforgeai/context/<name>.md not found; conventions section 3 lists six context files",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E221",
        subcommand: "context audit",
        condition: "context statement contradicts an ADR",
        message: "<file> line <n> states '<claim>'; <ADR-nnn> line <m> states '<counter>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E222",
        subcommand: "context audit",
        condition: "constraint ID reused",
        message: "CON-<nnn> is defined in <file-a> and <file-b>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E223",
        subcommand: "context audit",
        condition: "CA-2, a context file is not accepted",
        message: "<path> is status '<value>' with <n> open questions; context audit needs accepted and []",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E224",
        subcommand: "context audit",
        condition: "CA-4, an active CON is introduced by no ADR and traces to no REQ",
        message: "CON-<nnn> is introduced by no ADR and its source '<value>' resolves to no requirement",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E225",
        subcommand: "context audit",
        condition: "CA-6, an anti-pattern row is incomplete",
        message: "AP-<nnn> has <no detector | detector_kind '<value>' | source '<value>' which is not an active CON>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E226",
        subcommand: "context audit",
        condition: "CA-7, an ADR reference does not resolve",
        message: "<path> <id duplicates <other> | consumes <ID> which requirements.yaml does not define | introduces CON-<nnn> which the constraint index omits>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E227",
        subcommand: "context audit",
        condition: "CA-8, a supersession is incomplete",
        message: "<path> supersedes <ADR-nnn>, which is status '<value>'` / `<path> retires CON-<nnn>, which is status '<value>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E230",
        subcommand: "story validate",
        condition: "AC has no testable predicate",
        message: "<STORY-nnn> <AC-nnn> has no testable predicate; the grammar is Given/When/Then or a single assertion line",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E231",
        subcommand: "story validate",
        condition: "REQ reference unresolved",
        message: "<STORY-nnn> consumes <REQ-nnn>, which requirements.yaml does not define",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E232",
        subcommand: "story validate",
        condition: "dependency cycle",
        message: "dependency cycle: <A> -> <B> -> <A>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E233",
        subcommand: "story validate",
        condition: "sprint names an unknown story",
        message: "sprint.yaml lists <STORY-nnn>, which has no file",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E234",
        subcommand: "story validate",
        condition: "story has no ACs",
        message: "<STORY-nnn> defines no acceptance criteria",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E235",
        subcommand: "story validate",
        condition: "an epic requirement is covered by no story",
        message: "<EPIC-nnn> requirement <REQ-nnn> appears in the Requirements table of no story",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E236",
        subcommand: "story validate",
        condition: "an AC appears in no Covered by cell",
        message: "<STORY-nnn> <AC-nnn> appears in no Covered by cell of ## Requirements",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E237",
        subcommand: "story validate",
        condition: "declared file sets overlap",
        message: "<STORY-nnn> and <STORY-nnn> both declare <path>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E238",
        subcommand: "story validate",
        condition: "a cited UI spec is absent",
        message: "<STORY-nnn> cites <UI-nnn>, which .devforgeai/ui-specs/ does not hold",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E239",
        subcommand: "story files, commit",
        condition: "a path is outside the declared set",
        message: "<path> is outside the declared file set of <STORY-nnn>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E245",
        subcommand: "story validate",
        condition: "an AC covers two requirements",
        message: "<STORY-nnn> <AC-nnn> appears in the Covered by cell of <REQ-nnn> and <REQ-nnn>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E240",
        subcommand: "design lint",
        condition: "literal colour",
        message: "<path>:<line> uses the literal colour '<value>'; brand/tokens.json defines <nearest-token>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E241",
        subcommand: "design lint",
        condition: "literal type value",
        message: "<path>:<line> uses the literal <property> '<value>'; brand/tokens.json defines <nearest-token>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E242",
        subcommand: "design lint",
        condition: "unknown token reference",
        message: "<path>:<line> references token '<name>', which brand/tokens.json does not define",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E243",
        subcommand: "design lint --tokens",
        condition: "token group or leaf shape",
        message: "brand/tokens.json group '<group>' leaf '<leaf>' is <found>, expected <expected>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E244",
        subcommand: "design lint --tokens",
        condition: "undefined token in a UI spec",
        message: "<path>:<line> references token '<name>', which brand/tokens.json does not define",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E250",
        subcommand: "doc load",
        condition: "unknown document name",
        message: "'<name>' is not a document; the names are <list>",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E270",
        subcommand: "antipattern scan",
        condition: "an anti-pattern detector matched",
        message: "<AP-nnn> matched <path>:<line>: <text>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E271",
        subcommand: "worktree, commit",
        condition: "the project root is not a git work tree",
        message: "<path> is not a git work tree; run git init",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E272",
        subcommand: "worktree ensure",
        condition: "two stories declare a shared path",
        message: "<STORY-nnn> and <STORY-nnn> both declare <path>; one worktree at a time",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E273",
        subcommand: "worktree remove",
        condition: "the worktree has uncommitted or unmerged work",
        message: "<path> holds <n> uncommitted changes and <m> commits absent from <base_ref>; pass --force",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E260",
        subcommand: "doc accept",
        condition: "the document has no epics or no requirements",
        message: "requirements.yaml has no <epics | requirements>; nothing accepted",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E261",
        subcommand: "doc reopen",
        condition: "a cited id is neither REQ nor UI",
        message: "'<id>' is neither a REQ nor a UI id",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E262",
        subcommand: "explore prune",
        condition: "a path could not be removed",
        message: "removing <path> failed: <io message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E300",
        subcommand: "gate check, gate require, phase set",
        condition: "no gate for the phase",
        message: "gates.toml has no gate for phase '<phase>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E301",
        subcommand: "any reading gates",
        condition: "unknown check kind",
        message: "gates.toml gate '<phase>' check '<id>' has kind '<value>'; the kinds are <list>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E302",
        subcommand: "any reading gates",
        condition: "unknown key in a check",
        message: "gates.toml gate '<phase>' check '<id>' has key '<key>', which kind '<kind>' does not define",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E303",
        subcommand: "any reading gates or config",
        condition: "compiled minimum violated",
        message: "gates.toml gate '<phase>' omits required check kind '<kind>'` / `gates.toml gate '<phase>' sets <kind>.<key> to <value>, below the compiled minimum <floor>` / `config.toml sets <key> to <value>, below the compiled minimum <floor>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E304",
        subcommand: "any reading gates",
        condition: "`cli_min_version` above the binary",
        message: "gates.toml requires devforgeai <value> or newer; this binary is <version>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E305",
        subcommand: "any reading gates",
        condition: "duplicate phase or check id",
        message: "gates.toml defines phase '<phase>' twice` / `gates.toml defines check id '<id>' twice in gate '<phase>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E306",
        subcommand: "any reading gates",
        condition: "`send_back_to` absent or invalid",
        message: "gates.toml gate '<phase>' has on_fail = \"send_back\" and send_back_to = '<value>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E310",
        subcommand: "gate check",
        condition: "`tests_pass` with an empty command, `degraded = false`",
        message: "stack '<id>' has no test_command; set one in config.toml",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E311",
        subcommand: "gate check",
        condition: "test command exited non-zero",
        message: "test command '<cmd>' exited <code> for stack '<id>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E312",
        subcommand: "gate check",
        condition: "coverage report absent or unparsable",
        message: "coverage report not found at <globs>` / `coverage report <path> is not <format>: <parser message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E313",
        subcommand: "gate check",
        condition: "layer below threshold",
        message: "coverage for layer '<name>' is <actual>%, below the <min>% in config.toml",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E314",
        subcommand: "gate check",
        condition: "`lint_clean` with an empty command, `degraded = false`",
        message: "stack '<id>' has no lint_command; set one in config.toml",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E315",
        subcommand: "gate check",
        condition: "lint command exited non-zero",
        message: "lint command '<cmd>' exited <code> for stack '<id>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E316",
        subcommand: "gate check",
        condition: "no ingested block for a named verifier",
        message: "report <path> has no verifiers block for '<name>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E317",
        subcommand: "gate check",
        condition: "verifier ratio below minimum",
        message: "verifier '<name>' passed <p>/<t>, below min_ratio <r>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E318",
        subcommand: "gate check",
        condition: "command exceeded `timeout_secs`",
        message: "command '<cmd>' exceeded <n>s and was terminated",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E319",
        subcommand: "gate check",
        condition: "command could not be spawned",
        message: "command '<cmd>' could not start: <io message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E320",
        subcommand: "phase set",
        condition: "predecessor gate not passed",
        message: "phase '<phase>' needs gate '<pred>' PASS for <id>; the last result is <result>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E321",
        subcommand: "gate require",
        condition: "predecessor report absent or not PASS",
        message: "<phase> needs <pred> gate PASS for <id>; no report at <path>` / `<phase> needs <pred> gate PASS for <id>; the last result is <result> at <time>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E322",
        subcommand: "gate check",
        condition: "`field_in_enum` failed",
        message: "<path> field '<field>' is '<value>'; gate '<phase>' check '<id>' allows <list>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E330",
        subcommand: "gate check",
        condition: "`field_is_date` failed",
        message: "<path> field '<field>' is '<value>', expected <format>` / `<path> field '<field>' is not later than '<after_field>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E331",
        subcommand: "gate check",
        condition: "`length_between` failed",
        message: "<path> <field> holds <value> entries, expected <min> to <max>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E332",
        subcommand: "gate check",
        condition: "`fields_present` failed",
        message: "<path> <collection> entry '<id>' has no '<field>'` / `<path> '<path-key>' is null",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E333",
        subcommand: "gate check",
        condition: "`set_cover` failed",
        message: "<n> ids at <universe> are absent from <cover>: <first five>` / `<id> appears twice in <cover>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E334",
        subcommand: "gate check",
        condition: "`row_count_between` failed",
        message: "<path> section '<section>' holds <value> rows, expected <min> to <max>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E335",
        subcommand: "gate check",
        condition: "`column_matches` failed",
        message: "<path> section '<section>' column '<column>' value '<value>' is <malformed | duplicated>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E336",
        subcommand: "gate check",
        condition: "`column_contains_all` failed",
        message: "<value> is in <state_field> and absent from <path> section '<section>' column '<column>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E337",
        subcommand: "gate check",
        condition: "`elapsed_days_at_most` failed",
        message: "<value> days elapsed of <limit> allowed since <started_field>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E338",
        subcommand: "gate check",
        condition: "`report_metric` failed",
        message: "<metric> is <value>, expected <op> <limit>` / `report <path> has no metric '<metric>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E339",
        subcommand: "gate check",
        condition: "a condition key names a field that does not exist",
        message: "gate '<phase>' check '<id>' condition reads '<field>', which <path> does not define",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E323",
        subcommand: "gate check",
        condition: "`file_exists` failed",
        message: "gate '<phase>' check '<id>' found <n> of <min_count> paths; missing <list>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E324",
        subcommand: "gate check",
        condition: "`no_open_questions` failed",
        message: "<path> has <n> open questions",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E325",
        subcommand: "gate check",
        condition: "`ids_resolve` failed",
        message: "<n> references do not resolve: <first five>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E326",
        subcommand: "gate check",
        condition: "`doc_valid` failed",
        message: "<path> failed doc validate: <first code and message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E327",
        subcommand: "gate check",
        condition: "`context_audit` failed",
        message: "context audit found <n> problems; first: <message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E328",
        subcommand: "gate check",
        condition: "`story_valid` failed",
        message: "story validate found <n> problems; first: <message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E329",
        subcommand: "gate check",
        condition: "`design_tokens` failed",
        message: "design lint found <n> problems; first: <message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E341",
        subcommand: "gate check",
        condition: "`release_stories` failed",
        message: "<STORY-nnn> is status '<value>' with verify result '<result>'; the release needs <require_status> and <require_result>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E342",
        subcommand: "gate check",
        condition: "`deploy_manifest` failed",
        message: "<path> <is absent | does not parse | has no <key>> for platform '<platform>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E343",
        subcommand: "gate check",
        condition: "a manifest holds a literal secret",
        message: "<path>:<line> holds a literal secret",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E344",
        subcommand: "gate check",
        condition: "`docs_cover` failed",
        message: "<n> of <m> public symbols have no H3 heading in docs.api[]: <first five>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E345",
        subcommand: "gate check",
        condition: "a document path in a check does not resolve",
        message: "gates.toml check '<id>': path '<path>' does not resolve in <doc>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E346",
        subcommand: "gate check",
        condition: "`yaml_cites` found too few citations",
        message: "<doc>: <from>[<n>] id '<id>' cites <count> of <min> required",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E347",
        subcommand: "gate check",
        condition: "`yaml_cites` found an unknown citation",
        message: "<doc>: <from>[<n>] id '<id>' cites '<value>', which <into> does not define",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E348",
        subcommand: "gate check",
        condition: "`no_threshold_decrease` found a lowered floor",
        message: "<doc>: <from>[<n>] id '<id>' proposes <key> = <value>, below the compiled floor <floor>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E400",
        subcommand: "report show, handoff",
        condition: "report absent",
        message: ".devforgeai/reports/<id>-<phase>.yaml not found",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E401",
        subcommand: "report show, gate check, handoff",
        condition: "report unparsable",
        message: "<path> is not valid YAML: <parser message>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E410",
        subcommand: "report ingest",
        condition: "stdout is not the verifier JSON",
        message: "subagent '<name>' output is not devforgeai/verifier/1: <parser message>",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-E412",
        subcommand: "report ingest",
        condition: "no active ID for the verifier's phase",
        message: "state.toml has no active id for phase '<phase>'; nothing ingested",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-E413",
        subcommand: "report note",
        condition: "the note file fails the `devforgeai/build-note/1` schema",
        message: "<path> key '<key>' is <found>, expected <expected>; nothing written",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E421",
        subcommand: "report aggregate",
        condition: "the session root resolves outside the user's home",
        message: "session root '<path>' is outside <home>; sessions unreadable",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E430",
        subcommand: "report aggregate",
        condition: "neither or both of `<ID>` and `--since`",
        message: "pass one id (IDEA-nnn, EPIC-nnn, STORY-nnn, vX.Y.Z) or --since <YYYY-MM-DD>",
        exit: 3,
    },
    ErrorRow {
        code: "DFA-E500",
        subcommand: "trust pin",
        condition: "a Claude session is active",
        message: "trust pin does not run inside a Claude session; <var> is set",
        exit: 4,
    },
    ErrorRow {
        code: "DFA-E501",
        subcommand: "trust verify",
        condition: "`trust.toml` absent",
        message: "<home>/trust.toml not found; a human runs 'devforgeai trust pin' outside Claude",
        exit: 4,
    },
    ErrorRow {
        code: "DFA-E502",
        subcommand: "trust verify",
        condition: "no pin for this binary path",
        message: "no pin for <path> in trust.toml",
        exit: 4,
    },
    ErrorRow {
        code: "DFA-E503",
        subcommand: "trust verify",
        condition: "digest mismatch",
        message: "binary digest <actual> does not match the pin <expected>",
        exit: 4,
    },
    ErrorRow {
        code: "DFA-E504",
        subcommand: "trust verify",
        condition: "source digest drift during a session",
        message: "cli/ source digest <actual> differs from the pinned REVISION <expected> while a Claude session is active",
        exit: 4,
    },
    ErrorRow {
        code: "DFA-E510",
        subcommand: "trust pin",
        condition: "`cli/DIGEST` or `cli/REVISION` absent or malformed",
        message: "<path> is missing` / `<path> is malformed; release builds write it",
        exit: 4,
    },
    ErrorRow {
        code: "DFA-E511",
        subcommand: "trust pin, trust verify",
        condition: "current executable path unavailable",
        message: "the running executable path is unavailable: <io message>",
        exit: 4,
    },
    ErrorRow {
        code: "DFA-E512",
        subcommand: "trust pin, trust verify",
        condition: "`trust.toml` unparsable",
        message: "trust.toml is not valid TOML: <parser message>",
        exit: 4,
    },
    ErrorRow {
        code: "DFA-E900",
        subcommand: "any",
        condition: "filesystem error",
        message: "<operation> on <path> failed: <io message>",
        exit: 5,
    },
    ErrorRow {
        code: "DFA-E902",
        subcommand: "any",
        condition: "a subcommand or check kind is specified and stubbed in this build",
        message: "check kind '<kind>' is specified and not implemented in this build",
        exit: 5,
    },
    ErrorRow {
        code: "DFA-E901",
        subcommand: "any",
        condition: "atomic rename failed",
        message: "replacing <path> failed: <io message>; the temporary file is <tmp>",
        exit: 5,
    },
    ErrorRow {
        code: "DFA-W130",
        subcommand: "hook install",
        condition: "a Claude hook entry is already present",
        message: "<event> hook already present; left unchanged",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-W201",
        subcommand: "doc validate",
        condition: "`consumes` lists an ID the body does not cite",
        message: "<path> consumes <ID>, which the body does not cite",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-W210",
        subcommand: "phase set",
        condition: "the document whose status the phase advances is absent",
        message: "status not written; <path> not found",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-W202",
        subcommand: "doc validate",
        condition: "body cites an ID absent from `consumes`",
        message: "<path> cites <ID>, which consumes does not list",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-E340",
        subcommand: "gate check",
        condition: "`no_cycle` found a cycle",
        message: "deferral cycle: <A> -> <B> -> <A>",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-W243",
        subcommand: "commit",
        condition: "the stage set is empty",
        message: "no declared path changed; nothing committed",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-W310",
        subcommand: "gate check",
        condition: "a `warn` severity check failed",
        message: "check '<id>' failed with severity warn: <message>",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-W320",
        subcommand: "gate check",
        condition: "covered files match no layer glob, `unassigned_policy = \"report\"`",
        message: "<n> covered files match no layer glob",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-W411",
        subcommand: "report ingest",
        condition: "subagent absent from the registry",
        message: "subagent '<name>' is not in config.toml [[verifier]]; nothing ingested",
        exit: 0,
    },
    ErrorRow {
        code: "DFA-W500",
        subcommand: "trust verify",
        condition: "the pin predates the binary file time",
        message: "the pin predates the binary file time; digests still match",
        exit: 0,
    },
    // gate engine
    ErrorRow {
        code: "DFA-E349",
        subcommand: "gate check",
        condition: "`complexity_clean` failed or its stack selection names nothing",
        message: "complexity command '<command>' exited <code> for stack '<stack>'",
        exit: 1,
    },
    ErrorRow {
        code: "DFA-E350",
        subcommand: "gate check",
        condition: "a failing check produced no diagnostic code",
        message: "gate '<phase>' check '<id>' failed and named no code",
        exit: 1,
    },
    // hooks and docs
    ErrorRow {
        code: "DFA-W420",
        subcommand: "report aggregate",
        condition: "a report under reports/ does not parse",
        message: "<path> does not parse; it is excluded from the window",
        exit: 0,
    },
];

/// The code a subcommand or check kind that is specified and stubbed in this
/// build refuses with. Exit 5, the spec's internal-error class. The spec table
/// carries it as a row of its own.
pub const NOT_IMPLEMENTED: &str = "DFA-E902";

/// The exit code the spec table assigns to `code`, or `None` when the
/// table does not define it.
pub fn exit_for(code: &str) -> Option<i32> {
    ERROR_TABLE
        .iter()
        .find(|row| row.code == code)
        .map(|row| row.exit)
}

/// The spec row for `code`, or `None` when the table does not define it.
pub fn row(code: &str) -> Option<&'static ErrorRow> {
    ERROR_TABLE.iter().find(|row| row.code == code)
}
